"use client";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Newsletter from "@/components/shared/Newsletter";
import Footer from "@/components/shared/Footer";
import { useContext, useEffect } from "react";
import { GlobalContext } from "@/context/context";
import Cart from "@/components/shared/Cart";
import dynamic from "next/dynamic";
import { ToastContainer } from "react-toastify";
import client from "@/utils/StorefrontInit";
import { getCollections } from "@/utils/queries";
import Script from "next/script";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const GlobalContextProvider = dynamic(() => import("../context/context"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { customLayout, collections, setCollections } =
    useContext(GlobalContext);

  // async function fetchCollections() {
  //   try {
  //     const { data } = await client.request(getCollections, {
  //       variables: {
  //         first: 50,
  //         query: "",
  //       },
  //     });

  //     if (data) {
  //       setCollections(data.collections.nodes);
  //     }
  //   } catch (err: any) {
  //     console.log("Fetch Error: ", err);
  //   }
  // }

  useEffect(() => {
    // fetchCollections()
  }, []);

  // useEffect(() => {
  //   console.log("this is collections from context: ", collections);
  // }, [collections]);

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <GlobalContextProvider>
          <Cart />
          {customLayout === false && <Navbar />}
          {children}
          {customLayout === false && <Newsletter />}
          {customLayout === false && <Footer />}
          <ToastContainer />
        </GlobalContextProvider>
        <Script
          id="tawkto"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
              (function(){
              var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
              s1.async=true;
              s1.src='https://embed.tawk.to/6874e4ca1706a0190d63793d/1j049rebp';
              s1.charset='UTF-8';
              s1.setAttribute('crossorigin','*');
              s0.parentNode.insertBefore(s1,s0);
              })();
            `,
          }}
        />
      </body>
    </html>
  );
}
