"use client";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Newsletter from "@/components/shared/Newsletter";
import Footer from "@/components/shared/Footer";
import { useContext } from "react";
import { GlobalContext, GlobalContextProvider } from "@/context/context";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { customLayout } = useContext(GlobalContext);

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <GlobalContextProvider>
          {customLayout === false && <Navbar />}
          {children}
          {customLayout === false && <Newsletter />}
          {customLayout === false && <Footer />}
        </GlobalContextProvider>
      </body>
    </html>
  );
}
